baseurl: ''
exclude: ['README.md']
permalink: pretty
title_en: 'DLI National Training'
title_fr: 'Formation nationale de l’IDD'
email: 'statcan.maddli-damidd.statcan@canada.ca'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo-mobile.svg"
  desktop: "images/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: ''
heading_anchors: true

seo:
  meta_og_title: ""
  meta_og_type: ""
  meta_og_url: ""
  meta_og_image: ""
  meta_og_description: ""
  meta_twitter_card: "summary"
  meta_twitter_site: ""
  meta_twitter_creator: ""

future: true

collections:
  sessions:
    output: true
    future: true
    permalink: /:path/
  archive:
    output: true
    future: true
    permalink: /:path/
  posts:
    future: true
    output: true


defaults:
  - scope:
      type: sessions
    values:
      layout: session
      bodyClass: page-sessions-single
  - scope:
      type: archives
    values:
      layout: session
      bodyClass: page-sessions-single
  - scope:
      path: 'images'
    values:
      image: true


sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
